document.title = "the-uncredible-julian-episode-1";
var numPages = 5;
var curPage = 0;
var pages = new Array(5);
pages[0] = "pages/Page_1.jpg";
pages[1] = "pages/Page_2.jpg";
pages[2] = "pages/Page_3.jpg";
pages[3] = "pages/Page_4.jpg";
pages[4] = "pages/Page_5.jpg";
